import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { UserCog, AlertTriangle, Copy, Send, Link, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { useActiveHospital } from '@/hooks/useActiveHospital';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { ShiftType, StaffShift } from '@shared/schema';
import { ROLE_CONFIG, type StaffPoolEntry } from './PlannedStaffBox';
import { StaffRecurrenceContent } from './StaffRecurrenceDialog';

type StaffRole = StaffPoolEntry['role'];

interface WorklogLink {
  id: string;
  unitId: string;
  hospitalId: string;
  email: string;
  token: string;
  isActive: boolean;
  unitName: string;
}

interface StaffManagementDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  staff: StaffPoolEntry;
  hospitalId: string;
  selectedDate: Date;
}

export default function StaffManagementDialog({ open, onOpenChange, staff, hospitalId, selectedDate }: StaffManagementDialogProps) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const activeHospital = useActiveHospital();
  const isAdmin = activeHospital?.role === 'admin';
  const unitId = activeHospital?.unitId;

  const config = ROLE_CONFIG[staff.role as StaffRole];

  const [emailInput, setEmailInput] = useState(staff.email || '');
  const isAutoGenerated = staff.email?.endsWith('@staff.local') ?? false;

  // Save email mutation
  const saveEmailMutation = useMutation({
    mutationFn: async (newEmail: string) => {
      const res = await apiRequest('PATCH', `/api/admin/users/${staff.userId}/email`, {
        email: newEmail,
        hospitalId,
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.message || 'Failed to update email');
      }
      return res.json();
    },
    onSuccess: () => {
      toast({ title: t('common.success'), description: t('staffPool.emailUpdated') });
      queryClient.invalidateQueries({ queryKey: ['/api/staff-pool'] });
      // Invalidate worklog link query with old email, new one will be fetched
      queryClient.invalidateQueries({ queryKey: ['worklog-links-by-email'] });
    },
    onError: (error: Error) => {
      toast({ title: t('common.error'), description: error.message, variant: 'destructive' });
    },
  });

  // Fetch worklog links by email
  const currentEmail = saveEmailMutation.data?.email || emailInput;
  const isRealEmail = currentEmail && !currentEmail.endsWith('@staff.local');

  const { data: worklogLinks = [], isLoading: linksLoading } = useQuery<WorklogLink[]>({
    queryKey: ['worklog-links-by-email', hospitalId, currentEmail],
    queryFn: async () => {
      const res = await fetch(
        `/api/hospitals/${hospitalId}/worklog/links/by-email?email=${encodeURIComponent(currentEmail)}`,
        { credentials: 'include' }
      );
      if (!res.ok) return [];
      return res.json();
    },
    enabled: open && !!isRealEmail,
  });

  const existingLink = worklogLinks.length > 0 ? worklogLinks[0] : null;

  // Create worklog link mutation
  const createLinkMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest('POST', `/api/hospitals/${hospitalId}/units/${unitId}/worklog/links`, {
        email: currentEmail,
        sendEmail: true,
      });
      if (res.status === 409) {
        const data = await res.json();
        throw new Error(data.message || t('staffPool.linkAlreadyExists'));
      }
      if (!res.ok) throw new Error('Failed to create link');
      return res.json();
    },
    onSuccess: () => {
      toast({ title: t('common.success'), description: t('staffPool.linkCreated') });
      queryClient.invalidateQueries({ queryKey: ['worklog-links-by-email'] });
    },
    onError: (error: Error) => {
      toast({ title: t('common.error'), description: error.message, variant: 'destructive' });
    },
  });

  // Resend email mutation
  const resendMutation = useMutation({
    mutationFn: async (linkId: string) => {
      const res = await apiRequest('POST', `/api/hospitals/${hospitalId}/worklog/links/${linkId}/send`);
      if (!res.ok) throw new Error('Failed to send email');
      return res.json();
    },
    onSuccess: () => {
      toast({ title: t('common.success'), description: t('staffPool.linkSent') });
    },
    onError: () => {
      toast({ title: t('common.error'), description: t('staffPool.planError'), variant: 'destructive' });
    },
  });

  // Shift section
  const dateStr = `${selectedDate.getFullYear()}-${String(selectedDate.getMonth() + 1).padStart(2, '0')}-${String(selectedDate.getDate()).padStart(2, '0')}`;

  const { data: shiftTypes = [] } = useQuery<ShiftType[]>({
    queryKey: [`/api/shift-types/${hospitalId}`],
    enabled: open,
  });

  const { data: staffShifts = [] } = useQuery<StaffShift[]>({
    queryKey: [`/api/staff-shifts/${hospitalId}`, dateStr, dateStr],
    queryFn: async () => {
      const res = await fetch(`/api/staff-shifts/${hospitalId}?from=${dateStr}&to=${dateStr}`, { credentials: 'include' });
      if (!res.ok) return [];
      return res.json();
    },
    enabled: open && !!staff.userId,
  });

  const currentShift = staffShifts.find(s => s.userId === staff.userId && s.date === dateStr);
  const [shiftTypeId, setShiftTypeId] = useState<string>('');

  useEffect(() => {
    if (currentShift) setShiftTypeId(currentShift.shiftTypeId);
    else setShiftTypeId('');
  }, [currentShift]);

  const saveShiftMutation = useMutation({
    mutationFn: async () => {
      await apiRequest('POST', `/api/staff-shifts/${hospitalId}/assign`, {
        userId: staff.userId,
        date: dateStr,
        shiftTypeId: shiftTypeId || null,
        role: null,
      });
    },
    onSuccess: () => {
      toast({ title: t('shifts.saved', 'Shift saved') });
      queryClient.invalidateQueries({ queryKey: [`/api/staff-shifts/${hospitalId}`] });
    },
    onError: () => {
      toast({ title: t('common.error'), variant: 'destructive' });
    },
  });

  const handleCopyLink = (token: string) => {
    const url = `${window.location.origin}/worklog/${token}`;
    navigator.clipboard.writeText(url);
    toast({ title: t('common.success'), description: t('staffPool.linkCopied') });
  };

  const handleSaveEmail = () => {
    const trimmed = emailInput.trim();
    if (!trimmed) return;
    saveEmailMutation.mutate(trimmed);
  };

  const emailChanged = emailInput.trim() !== (staff.email || '') && emailInput.trim() !== '';

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <UserCog className="h-4 w-4" />
            {staff.name}
            <Badge variant="secondary" className={`text-xs ${config?.bgClass}`}>
              {t(config?.labelKey || '')}
            </Badge>
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="worker-info" className="w-full">
          <TabsList className="w-full">
            <TabsTrigger value="worker-info" className="flex-1 text-xs">
              {t('staffPool.workerInfo')}
            </TabsTrigger>
            <TabsTrigger value="recurring" className="flex-1 text-xs">
              {t('staffPool.recurringPlanning')}
            </TabsTrigger>
          </TabsList>

          <TabsContent value="worker-info" className="mt-4 space-y-4">
            {/* Email section */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">E-Mail</Label>
              {isAutoGenerated && (
                <div className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400">
                  <AlertTriangle className="h-3.5 w-3.5" />
                  {t('staffPool.emailLocalWarning')}
                </div>
              )}
              <div className="flex gap-2">
                <Input
                  type="email"
                  value={emailInput}
                  onChange={(e) => setEmailInput(e.target.value)}
                  placeholder="name@example.com"
                  className="h-8 text-sm"
                  disabled={!isAdmin}
                />
                {isAdmin && (
                  <Button
                    size="sm"
                    className="h-8 text-xs whitespace-nowrap"
                    onClick={handleSaveEmail}
                    disabled={!emailChanged || saveEmailMutation.isPending}
                  >
                    {saveEmailMutation.isPending && <Loader2 className="h-3 w-3 mr-1 animate-spin" />}
                    {t('staffPool.saveEmail')}
                  </Button>
                )}
              </div>
              {!isAdmin && (
                <p className="text-xs text-muted-foreground">{t('staffPool.adminRequiredForEmail')}</p>
              )}
            </div>

            {/* Shift section */}
            {isAdmin && (
              <div className="space-y-2 pt-2 border-t">
                <Label className="text-sm font-medium">{t('shifts.popover.shift', 'Shift')}</Label>
                <div className="flex gap-2">
                  <Select value={shiftTypeId || '__none__'} onValueChange={(v) => setShiftTypeId(v === '__none__' ? '' : v)}>
                    <SelectTrigger className="h-9 text-sm flex-1">
                      <SelectValue placeholder={t('shifts.popover.shiftPlaceholder', 'Select shift')} />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="__none__">{t('shifts.popover.shiftNone', 'No shift')}</SelectItem>
                      {shiftTypes.map((s) => (
                        <SelectItem key={s.id} value={s.id}>
                          <span className="inline-flex items-center gap-1.5">
                            <span className="h-2.5 w-2.5 rounded-sm inline-block" style={{ background: s.color }} />
                            {s.name} ({s.startTime}–{s.endTime})
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={saveShiftMutation.isPending || (shiftTypeId === (currentShift?.shiftTypeId ?? ''))}
                    onClick={() => saveShiftMutation.mutate()}
                  >
                    {saveShiftMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : t('common.save', 'Save')}
                  </Button>
                </div>
                {currentShift && shiftTypes.find(s => s.id === currentShift.shiftTypeId) && (
                  <div className="text-xs text-muted-foreground">
                    {t('shifts.currentlyAssigned', 'Currently')}: {shiftTypes.find(s => s.id === currentShift.shiftTypeId)!.name}
                  </div>
                )}
              </div>
            )}

            {/* Worklog link section */}
            {isRealEmail && (
              <div className="space-y-2">
                <Label className="text-sm font-medium">{t('staffPool.worklogLinkStatus')}</Label>
                {linksLoading ? (
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <Loader2 className="h-3 w-3 animate-spin" />
                    {t('common.loading')}
                  </div>
                ) : existingLink ? (
                  <div className="flex items-center gap-2 p-2 rounded border bg-muted/30">
                    <Link className="h-3.5 w-3.5 text-green-600" />
                    <span className="text-xs flex-1">
                      {existingLink.unitName}
                    </span>
                    <Button
                      size="sm"
                      variant="outline"
                      className="h-6 text-xs px-2"
                      onClick={() => handleCopyLink(existingLink.token)}
                    >
                      <Copy className="h-3 w-3 mr-1" />
                      {t('staffPool.copyLink')}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      className="h-6 text-xs px-2"
                      onClick={() => resendMutation.mutate(existingLink.id)}
                      disabled={resendMutation.isPending}
                    >
                      {resendMutation.isPending ? (
                        <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                      ) : (
                        <Send className="h-3 w-3 mr-1" />
                      )}
                      {t('staffPool.resendEmail')}
                    </Button>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <p className="text-xs text-muted-foreground">{t('staffPool.noWorklogLink')}</p>
                    <Button
                      size="sm"
                      className="h-7 text-xs"
                      onClick={() => createLinkMutation.mutate()}
                      disabled={createLinkMutation.isPending}
                    >
                      {createLinkMutation.isPending ? (
                        <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                      ) : (
                        <Send className="h-3 w-3 mr-1" />
                      )}
                      {t('staffPool.createWorklogLink')}
                    </Button>
                  </div>
                )}
              </div>
            )}
          </TabsContent>

          <TabsContent value="recurring" className="mt-4">
            <StaffRecurrenceContent
              staff={staff}
              hospitalId={hospitalId}
              selectedDate={selectedDate}
              onClose={() => onOpenChange(false)}
            />
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
