import type { Express } from "express";
import authRouter from "./auth";
import inventoryRouter from "./inventory";
import adminRouter from "./admin";
import checklistsRouter from "./checklists";
import anesthesiaRouter from "./anesthesia";
import businessRouter from "./business";
import clinicRouter from "./clinic";
import surgeonChecklistsRouter from "./surgeonChecklists";
import chatRouter from "./chat";
import questionnaireRouter from "./questionnaire";
import camerasRouter from "./cameras";
import billingRouter from "./billing";
import externalSurgeryRouter from "./externalSurgery";
import itemsRouter from "./items";
import ordersRouter from "./orders";
import controlledRouter from "./controlled";
import worklogRouter from "./worklog";
import notesRouter from "./notes";
import aiRouter from "./ai";
import importJobsRouter from "./importJobs";
import hospitalsRouter from "./hospitals";

export function registerDomainRoutes(app: Express) {
  app.use(authRouter);
  app.use(inventoryRouter);
  app.use(itemsRouter);
  app.use(ordersRouter);
  app.use(adminRouter);
  app.use(checklistsRouter);
  app.use(anesthesiaRouter);
  app.use(businessRouter);
  app.use(clinicRouter);
  app.use(surgeonChecklistsRouter);
  app.use(chatRouter);
  app.use(questionnaireRouter);
  app.use(camerasRouter);
  app.use(billingRouter);
  app.use(externalSurgeryRouter);
  app.use(controlledRouter);
  app.use(worklogRouter);
  app.use(notesRouter);
  app.use(aiRouter);
  app.use(importJobsRouter);
  app.use(hospitalsRouter);
}
