import { Router, type Request, type Response } from "express";

export const LLMS_TXT = `# Viali API

> Viali's public API for booking links, lead ingestion, and
> ad-platform conversion reporting.

## Docs

- [API reference](/api): full human + agent docs
- [Leads webhook](/api#leads-webhook)
- [Conversions API](/api#conversions-api)
- [Booking link parameters](/api#booking-link)

## Auth

Per-hospital API keys, generated by a hospital admin at
/admin/integrations (tab: API Key). Passed as \`?key=\` query param.
`;

export function llmsTxtHandler(_req: Request, res: Response) {
  res.type("text/plain; charset=utf-8").send(LLMS_TXT);
}

const router = Router();
router.get("/llms.txt", llmsTxtHandler);
export default router;
